# Generated by Django 5.1.1 on 2024-10-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='typ',
            new_name='type',
        ),
    ]
